name = "auto-parts-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
GOOGLE_SPREADSHEET_ID = "11oQUiWgY3M07dqA8nftfCGwe-CuvbtIf5WKf7g9cnlE"

[build]
command = ""
